### ISSUE TITLE
It's not a bug, it's a feature: does misclassification affect bug localization?

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#172] opened 2015-02-13 19:45 UTC
paper:http://dl.acm.org/citation.cfm?id=2597105&CFID=626469285&CFTOKEN=55193119
dataset:http://www.st.cs.uni-saarland.de/softevo/bugclassify/

**Comment by vivekaxl** [comment] 2015-02-13 19:58
typo corrected!

**Comment by ShirinAkbari** [comment] 2015-02-13 20:49
Title: It's not a bug, it's a feature: does misclassification affect bug localization?
Email of Author : {kochharps.2012,btdle.2012,davidlo}@smu.edu.sg

Abstract : "Bug localization refers to the task of automatically processing
bug reports to locate source code files that are responsible
for the bugs. Many bug localization techniques have
been proposed in the literature. These techniques are often
evaluated on issue reports that are marked as bugs by their
reporters in issue tracking systems. However, recent findings
by Herzig et al. find that a substantial number of issue reports
marked as bugs, are not bugs but other kinds of issues
like refactorings, request for enhancement, documentation
changes, test case creation, and so on. Herzig et al. report
that these misclassifications affect bug prediction, namely
the task of predicting which files are likely to be buggy in the
future. In this work, we investigate whether these misclassifications
also affect bug localization. To do so, we analyze
issue reports that have been manually categorized by Herzig
et al. and apply a bug localization technique to recover a
ranked list of candidate buggy files for each issue report. We
then evaluate whether the quality of ranked lists of reports
reported as bugs is the same as that of real bug reports. Our
findings shed light that there is a need for additional cleaning
steps to be performed on issue reports before they are
used to evaluate bug localization techniques."

**Comment by reesjones** [comment] 2015-03-11 15:37
Needs better context notes. See [this example](https://github.com/opensciences/opensciences.github.io/issues/156) or [this example](http://openscience.us/repo/issues/bugsal.html) as a reference.

Context notes are directly inserted into the actual repository (like [this](http://openscience.us/repo/issues/bugsal.html)), so good context notes are necessary for putting the datasets into the repo in a timely fashion.

**Closed** 2015-03-12 17:45 UTC
Labels: 4a. Target Paper, 4f. Needs new/better context notes

**Comment by CarterPape** [comment] 2015-03-12 18:09
This was closed because it is a duplicate of issue #142
